#!/bin/bash

if [ -z "$1" ]
then
      AWS_PROFILE="$AWS_PROFILE" _awswitch
else
      AWS_PROFILE="$AWS_PROFILE"
fi

chosen_profile="$(cat ~/.awswitch)"

if [ -z "$chosen_profile" ]
then
  unset AWS_PROFILE
else
  export AWS_PROFILE="$chosen_profile"
fi
